import type { User, UserId } from "./types";

/** Mock mentor users for search/listing until Convex-backed mentor list exists. */
export const mockMentors: User[] = [
  {
    _id: "mentor-1" as UserId,
    _creationTime: 0,
    name: "Emma Wilson",
    email: "emma.wilson@example.com",
    bio: "Senior ML engineer with 10+ years of experience in NLP and computer vision. Passionate about helping the next generation of engineers.",
    location: "San Francisco, CA",
    profilePictureUrl: "",
    title: "Senior ML Engineer at TechCorp",
    dateOfBirth: 0,
    gender: "",
    nationality: "",
    tokenIdentifier: "mock-mentor-1",
    phoneNumber: "",
    education: [],
    experience: [],
    onboardingStatus: "mentee_profile_setup_complete",
    createdAt: 0,
    mentorProfile: {
      yearsOfExperience: 12,
      industries: ["Technology", "AI/ML"],
      expertise: ["Machine Learning", "NLP", "Computer Vision", "Python"],
      maxMentees: 3,
      isAvailable: true,
    },
  },
  {
    _id: "mentor-2" as UserId,
    _creationTime: 0,
    name: "Alex Johnson",
    email: "alex.johnson@example.com",
    bio: "Full-stack developer turned engineering manager. I help mentees navigate career transitions and level up their technical skills.",
    location: "New York, NY",
    profilePictureUrl: "",
    title: "Engineering Manager at StartupX",
    dateOfBirth: 0,
    gender: "",
    nationality: "",
    tokenIdentifier: "mock-mentor-2",
    phoneNumber: "",
    education: [],
    experience: [],
    onboardingStatus: "mentee_profile_setup_complete",
    createdAt: 0,
    mentorProfile: {
      yearsOfExperience: 8,
      industries: ["Technology", "Fintech"],
      expertise: ["Full Stack", "React", "Node.js", "Leadership"],
      maxMentees: 2,
      isAvailable: true,
    },
  },
  {
    _id: "mentor-3" as UserId,
    _creationTime: 0,
    name: "Sarah Chen",
    email: "sarah.chen@example.com",
    bio: "Data scientist specializing in healthcare analytics. Previously at Google Health and now leading a data team at a biotech startup.",
    location: "Boston, MA",
    profilePictureUrl: "",
    title: "Lead Data Scientist at BioHealth",
    dateOfBirth: 0,
    gender: "",
    nationality: "",
    tokenIdentifier: "mock-mentor-3",
    phoneNumber: "",
    education: [],
    experience: [],
    onboardingStatus: "mentee_profile_setup_complete",
    createdAt: 0,
    mentorProfile: {
      yearsOfExperience: 7,
      industries: ["Healthcare", "Technology"],
      expertise: ["Data Science", "Statistics", "Python", "Healthcare Analytics"],
      maxMentees: 2,
      isAvailable: true,
    },
  },
  {
    _id: "mentor-4" as UserId,
    _creationTime: 0,
    name: "Marcus Rivera",
    email: "marcus.rivera@example.com",
    bio: "Cloud architect with deep expertise in AWS and distributed systems. I enjoy mentoring engineers who want to scale their infrastructure knowledge.",
    location: "Austin, TX",
    profilePictureUrl: "",
    title: "Principal Cloud Architect at CloudScale",
    dateOfBirth: 0,
    gender: "",
    nationality: "",
    tokenIdentifier: "mock-mentor-4",
    phoneNumber: "",
    education: [],
    experience: [],
    onboardingStatus: "mentee_profile_setup_complete",
    createdAt: 0,
    mentorProfile: {
      yearsOfExperience: 15,
      industries: ["Technology", "Cloud Computing"],
      expertise: ["AWS", "Distributed Systems", "Kubernetes", "DevOps"],
      maxMentees: 4,
      isAvailable: false,
    },
  },
  {
    _id: "mentor-5" as UserId,
    _creationTime: 0,
    name: "Priya Patel",
    email: "priya.patel@example.com",
    bio: "Product designer and UX researcher. I help mentees build user-centered design skills and grow their design careers.",
    location: "Seattle, WA",
    profilePictureUrl: "",
    title: "Senior Product Designer at DesignCo",
    dateOfBirth: 0,
    gender: "",
    nationality: "",
    tokenIdentifier: "mock-mentor-5",
    phoneNumber: "",
    education: [],
    experience: [],
    onboardingStatus: "mentee_profile_setup_complete",
    createdAt: 0,
    mentorProfile: {
      yearsOfExperience: 9,
      industries: ["Technology", "Design"],
      expertise: ["UX Design", "User Research", "Figma", "Design Systems"],
      maxMentees: 3,
      isAvailable: true,
    },
  },
];
